#
# Diese Konfigurationsdatei ist für Einstellungen gedacht, die sich auf dein
# gesamtes Blog auswirken. Die Werte werden normalerweise einmal eingerichtet 
# und danach nur noch selten verändert. 
# Wenn du diese Datei sehr häufiger bearbeitest, solltest du die Datendateien-
# funktion von Jekyll verwenden. Mehr dazu unter:
# https://jekyllrb.com/docs/datafiles/
#
# Aus technischen Gründen wird diese Datei *NICHT* automatisch neu geladen, 
# wenn du die lokale Vorschau mit `jekyll serve` oder `bundle exec jekyll serve`
# verwendest. Wenn du diese Datei änderst, starte den Serverprozess neu.
# 
# Benötigst du Hilfe beim YAML-Syntax, benutze folgende Kurzreferenzen:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
################################################################################
#
# Seiten Variablen
#
################################################################################
#
# Seiten Variablen werden verwendet, um deine neue Site zu personalisieren. Wenn 
# du in die HTML-Dateien schaust, kannst du sehen, dass du über {{site.title}}, 
# {{site.email}} usw. darauf zugreifen kannst. Du kannst jede gewünschte 
# benutzerdefinierte Variable erstellen, auf die du dann in deinen Vorlagen über 
# {{site.myvariable}} zugreifen kannst.
#
# Der Titel der Website
title: Der Titel der Website

# Autor der Website
author:
  name: mgerzabek
  email: me@michaelgerzabek.com
  display: Michael Gerzabek

# Die spitze Klammer erlaubt mehrzeilige Inhalte; 
# damit endet der Feldwert für "description:" bei "locale:" 
description: > 
  Beschreibe hier deine neue Website. Du kannst diese Inhalte in _config.yml 
  bearbeiten. Dieser Text wird im Dokumentkopf deiner Website angezeigt – damit
  auch in den Google-Suchergebnisse und in der Seitebeschreibung in feed.xml.
  
since: 1968
  
# Was immer für dich passt…    
locale: "de-AT"
  
# Wenn du Google Analytics verwendest, dann über den Google Tag Manager;
# einfach die folgende Zeile auskommentieren und die Tag-Id angeben
# gtm: 
  
# Customizing Werte für das Theme  
klartext: 
  
  # Wie der Formatstring aufgebaut ist, erfährst du in der Dokumentation von
  # Shopify;
  # https://shopify.github.io/liquid/filters/date/ 
  #date_format: "%d. %B %y"
  
  # Links zu social media accounts in der Fußzeile mit display: true
  # aktivieren und dann die entsprechenden Platformen mit dem Benutzernamen
  # versehen und auskommentieren
  social:
    display: true
    facebook: mgerzabek 
    # flickr: 
    github: mgerzabek  
    instagram: mgerzabek 
    linkedin: mgerzabek 
    # pinterest:
    # stackoverflow: 
    # telegram: 
    twitter: mgerzabek 
    # youtube:
    #   user:
    #   channel:
    #   name: 

## Kramdown settings
kramdown:  
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
  footnote_backlink: ▲
  parse_block_html: true
      
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Von der Verarbeitung ausschließen.
# Die folgenden Elemente werden standardmäßig nicht verarbeitet.
# Alle Elemente, die hier unter der `exclude:` aufgeführt sind, werden 
# automatisch zur internen Ausschlussliste hinzugefügt.
# Ausgeschlossene Elemente können verarbeitet werden, indem die Verzeichnisse 
# oder der Dateipfad ihrer Einträge explizit in `include:` aufgeführt werden.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - .idea/
   - Gemfile
   - Gemfile.lock
