name: Copy mgerzabek/klartext theme folders to pragmaticag/extended

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout mgerzabek/klartext
        uses: actions/checkout@v2
        with:
          path: klartext
          
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
  
      - name: Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: false
      
      - name: Checkout pragmaticag/extended
        uses: actions/checkout@v2
        with:
          repository: mgerzabek/extended
          token: ${{ secrets.KLARTEXT_PAT }}
          path: extended
          
      - name: Copy files
        run: |
          cp -u ./klartext/_includes/button/cta.html ./extended/_includes/button/cta.html
          cp -u ./klartext/_includes/button/cta.w.alt.text.html ./extended/_includes/button/cta.w.alt.text.html
          cp -u ./klartext/_includes/icons/external-link.html ./extended/_includes/icons/external-link.html
          cp -u ./klartext/_includes/icons/link.html ./extended/_includes/icons/link.html
          cp -u ./klartext/_includes/testimonial/basic.html ./extended/_includes/testimonial/basic.html
          cp -u ./klartext/_includes/audio.html ./extended/_includes/audio.html
          cp -u ./klartext/_includes/credit.html ./extended/_includes/credit.html
          cp -u ./klartext/_includes/custom-head.html ./extended/_includes/custom-head.html
          cp -u ./klartext/_includes/custom-pre-closing-body.html ./extended/_includes/custom-pre-closing-body.html
          cp -u ./klartext/_includes/datum.html ./extended/_includes/datum.html
          cp -u ./klartext/_includes/figure.html ./extended/_includes/figure.html
          cp -u ./klartext/_includes/footer.html ./extended/_includes/footer.html
          cp -u ./klartext/_includes/header.html ./extended/_includes/header.html
          cp -u ./klartext/_includes/sidebar.html ./extended/_includes/sidebar.html
          cp -u ./klartext/_includes/skin.html ./extended/_includes/skin.html
          cp -u ./klartext/_includes/social.html ./extended/_includes/social.html
          cp -u ./klartext/_includes/youtube.html ./extended/_includes/youtube.html
          cp -u ./klartext/_layouts/landing.html ./extended/_layouts/landing.html
          cp -u ./klartext/_layouts/page.html ./extended/_layouts/page.html
          cp -u ./klartext/_layouts/post.html ./extended/_layouts/post.html
          cp -u ./klartext/_layouts/video.html ./extended/_layouts/video.html
          cp  ./klartext/_site/assets/style.css ./extended/assets/klartext.css
          cp  ./klartext/_site/assets/style.css.map ./extended/assets/klartext.css.map
          cd klartext
          MESSAGE="$(git log -1 --pretty=%B)"
          cd ../extended
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "klartext: $MESSAGE"
          git push
