name: Copy mgerzabek/klartext theme folders to mgerzabek/extended

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout mgerzabek/klartext
        uses: actions/checkout@v3
        with:
          path: klartext
          
      - name: Checkout mgerzabek/extended
        uses: actions/checkout@v3
        with:
          repository: mgerzabek/extended
          path: extended
          
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
  
      - name: Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          jekyll_src: klartext
      
      - name: Copy files & Commit changes (if any…)
        run: |
          chmod +x ./klartext/.github/cc.sh
          ./klartext/.github/cc.sh
